In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.13.0


In [2]:
A = tf.constant([[3,6],[9,13]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 13]])>

In [3]:
A.shape, A.ndim, tf.size(A)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [4]:
B = tf.random.uniform(shape=(5,300))
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.906996  , 0.05264068, 0.8837917 , ..., 0.00838149, 0.51438415,
        0.7319132 ],
       [0.6169375 , 0.11306345, 0.88712025, ..., 0.6234515 , 0.94197667,
        0.32083464],
       [0.6544461 , 0.0098933 , 0.99108875, ..., 0.7229793 , 0.78694904,
        0.35929656],
       [0.04143286, 0.15169597, 0.49292696, ..., 0.49143088, 0.9247993 ,
        0.30824327],
       [0.9536054 , 0.5312836 , 0.5170649 , ..., 0.65626204, 0.01952422,
        0.8250445 ]], dtype=float32)>

In [5]:
B2 = tf.random.uniform(shape=(5,300))
B2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.04106534, 0.25786602, 0.8497628 , ..., 0.0208205 , 0.16249359,
        0.41352582],
       [0.5620003 , 0.5988157 , 0.38109636, ..., 0.9169766 , 0.22795665,
        0.22411323],
       [0.6216403 , 0.6245887 , 0.91212845, ..., 0.5979295 , 0.45733285,
        0.79731786],
       [0.88555753, 0.92930627, 0.3795328 , ..., 0.37148464, 0.69283044,
        0.23990107],
       [0.47483218, 0.5634407 , 0.49057758, ..., 0.62156713, 0.37518632,
        0.31964588]], dtype=float32)>

In [6]:
tf.linalg.matmul(B,tf.transpose(B2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.51321 , 79.69414 , 73.188034, 78.25601 , 73.31657 ],
       [67.8416  , 81.411545, 68.75498 , 77.387856, 72.35478 ],
       [71.051346, 82.854095, 74.07722 , 77.80025 , 76.01871 ],
       [70.12578 , 79.85254 , 70.84149 , 75.99031 , 72.21051 ],
       [73.547134, 81.271164, 75.54933 , 80.15887 , 74.09419 ]],
      dtype=float32)>

In [7]:
tf.tensordot(B, tf.transpose(B2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.51321 , 79.69414 , 73.188034, 78.25601 , 73.31657 ],
       [67.8416  , 81.411545, 68.75498 , 77.387856, 72.35478 ],
       [71.051346, 82.854095, 74.07722 , 77.80025 , 76.01871 ],
       [70.12578 , 79.85254 , 70.84149 , 75.99031 , 72.21051 ],
       [73.547134, 81.271164, 75.54933 , 80.15887 , 74.09419 ]],
      dtype=float32)>

In [8]:
C = tf.random.uniform(shape=(224,224,3))
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.55519414, 0.43819904, 0.42372024],
        [0.7662144 , 0.5435121 , 0.4341309 ],
        [0.3023547 , 0.44264483, 0.6786245 ],
        ...,
        [0.8950914 , 0.6341214 , 0.88275707],
        [0.67736304, 0.9266294 , 0.66529584],
        [0.0373019 , 0.80668867, 0.48856354]],

       [[0.23336935, 0.51277745, 0.2129705 ],
        [0.7253517 , 0.78689253, 0.6661117 ],
        [0.44836283, 0.46970856, 0.07632482],
        ...,
        [0.05752409, 0.66828215, 0.92733467],
        [0.15661371, 0.30226815, 0.4793439 ],
        [0.5325519 , 0.06788731, 0.14514685]],

       [[0.9100404 , 0.50855005, 0.7019365 ],
        [0.26820433, 0.99639404, 0.2027998 ],
        [0.86102796, 0.27787006, 0.19413781],
        ...,
        [0.5621009 , 0.41254568, 0.49065006],
        [0.7069876 , 0.2075615 , 0.77780914],
        [0.70012355, 0.91840076, 0.49340832]],

       ...,

       [[0.49231255, 0.3375609 , 0.50006187],
        [0.51

In [9]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999774>

In [10]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=4.887581e-06>

In [11]:
D = tf.random.uniform(shape=[50])
D

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.684518  , 0.66087794, 0.12107265, 0.76440144, 0.41605973,
       0.34865594, 0.75414455, 0.23946548, 0.94775176, 0.8931614 ,
       0.97620296, 0.28570735, 0.27612543, 0.61585534, 0.20484746,
       0.648883  , 0.40148306, 0.47140765, 0.3980093 , 0.02653384,
       0.3458562 , 0.00938225, 0.27829683, 0.8171861 , 0.9895662 ,
       0.2683637 , 0.5147207 , 0.4345895 , 0.2364316 , 0.6753231 ,
       0.95732045, 0.87796736, 0.01003957, 0.9437957 , 0.73573124,
       0.9775748 , 0.76061463, 0.06400788, 0.3517568 , 0.44553196,
       0.02370417, 0.72926545, 0.37711442, 0.30050302, 0.47686243,
       0.5573027 , 0.51043296, 0.866236  , 0.6829078 , 0.12525475],
      dtype=float32)>

In [12]:
tf.argmax(D)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [13]:
D[tf.argmax(D)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9895662>

In [14]:
E = tf.random.uniform(shape=(1,224,224,3))
E

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.10890734, 0.46951342, 0.6521529 ],
         [0.7791221 , 0.75452304, 0.62792706],
         [0.3388418 , 0.31224298, 0.06012154],
         ...,
         [0.41060734, 0.41142976, 0.6557027 ],
         [0.532843  , 0.90604806, 0.49662626],
         [0.82205033, 0.6702162 , 0.44314146]],

        [[0.54553723, 0.20562387, 0.03530324],
         [0.8464887 , 0.6473149 , 0.06413674],
         [0.74744344, 0.03967547, 0.5085527 ],
         ...,
         [0.7032496 , 0.7040013 , 0.05422604],
         [0.6213443 , 0.6897955 , 0.90337276],
         [0.43778324, 0.04855061, 0.6534488 ]],

        [[0.58766794, 0.08989298, 0.25542343],
         [0.8974407 , 0.9078132 , 0.5249603 ],
         [0.20265639, 0.86823714, 0.587934  ],
         ...,
         [0.6970544 , 0.5079315 , 0.33917296],
         [0.18656588, 0.7982329 , 0.01329887],
         [0.6222918 , 0.33737075, 0.42933428]],

        ...,

        [[0.21041751, 0.14028811, 

In [15]:
tf.squeeze(E)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.10890734, 0.46951342, 0.6521529 ],
        [0.7791221 , 0.75452304, 0.62792706],
        [0.3388418 , 0.31224298, 0.06012154],
        ...,
        [0.41060734, 0.41142976, 0.6557027 ],
        [0.532843  , 0.90604806, 0.49662626],
        [0.82205033, 0.6702162 , 0.44314146]],

       [[0.54553723, 0.20562387, 0.03530324],
        [0.8464887 , 0.6473149 , 0.06413674],
        [0.74744344, 0.03967547, 0.5085527 ],
        ...,
        [0.7032496 , 0.7040013 , 0.05422604],
        [0.6213443 , 0.6897955 , 0.90337276],
        [0.43778324, 0.04855061, 0.6534488 ]],

       [[0.58766794, 0.08989298, 0.25542343],
        [0.8974407 , 0.9078132 , 0.5249603 ],
        [0.20265639, 0.86823714, 0.587934  ],
        ...,
        [0.6970544 , 0.5079315 , 0.33917296],
        [0.18656588, 0.7982329 , 0.01329887],
        [0.6222918 , 0.33737075, 0.42933428]],

       ...,

       [[0.21041751, 0.14028811, 0.5654559 ],
        [0.90

In [16]:
D

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.684518  , 0.66087794, 0.12107265, 0.76440144, 0.41605973,
       0.34865594, 0.75414455, 0.23946548, 0.94775176, 0.8931614 ,
       0.97620296, 0.28570735, 0.27612543, 0.61585534, 0.20484746,
       0.648883  , 0.40148306, 0.47140765, 0.3980093 , 0.02653384,
       0.3458562 , 0.00938225, 0.27829683, 0.8171861 , 0.9895662 ,
       0.2683637 , 0.5147207 , 0.4345895 , 0.2364316 , 0.6753231 ,
       0.95732045, 0.87796736, 0.01003957, 0.9437957 , 0.73573124,
       0.9775748 , 0.76061463, 0.06400788, 0.3517568 , 0.44553196,
       0.02370417, 0.72926545, 0.37711442, 0.30050302, 0.47686243,
       0.5573027 , 0.51043296, 0.866236  , 0.6829078 , 0.12525475],
      dtype=float32)>

In [17]:
depth = tf.cast(tf.shape(D)[0], dtype=tf.int32)
depth

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [18]:
tf.one_hot(tf.range(depth), depth=depth)

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)>